// Copyright (c) 2026 Studio Pyro
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum PlatformOperationMode { production, test, testFailure }

enum PlatformStoreStatus { available, notInstalled, disabled, invalid }

enum PlatformOwnedProductFilter { item, subscription, all }

/// `ProductVo` field for field. Kotlin sends a missing string as `""` and
/// Dart does all interpretation.
class PlatformProduct {
  PlatformProduct({
    required this.itemId,
    required this.itemName,
    this.itemPrice,
    required this.itemPriceString,
    required this.currencyUnit,
    required this.currencyCode,
    required this.itemDesc,
    required this.type,
    required this.subscriptionDurationUnit,
    required this.subscriptionDurationMultiplier,
    required this.tieredSubscriptionYN,
    required this.tieredPrice,
    required this.tieredPriceString,
    required this.tieredSubscriptionDurationUnit,
    required this.tieredSubscriptionDurationMultiplier,
    required this.tieredSubscriptionCount,
    required this.showStartDate,
    required this.showEndDate,
    required this.itemImageUrl,
    required this.itemDownloadUrl,
    required this.freeTrialPeriod,
    required this.json,
  });

  String itemId;

  String itemName;

  double? itemPrice;

  String itemPriceString;

  String currencyUnit;

  String currencyCode;

  String itemDesc;

  String type;

  String subscriptionDurationUnit;

  String subscriptionDurationMultiplier;

  String tieredSubscriptionYN;

  String tieredPrice;

  String tieredPriceString;

  String tieredSubscriptionDurationUnit;

  String tieredSubscriptionDurationMultiplier;

  String tieredSubscriptionCount;

  String showStartDate;

  String showEndDate;

  String itemImageUrl;

  String itemDownloadUrl;

  String freeTrialPeriod;

  String json;

  List<Object?> _toList() {
    return <Object?>[
      itemId,
      itemName,
      itemPrice,
      itemPriceString,
      currencyUnit,
      currencyCode,
      itemDesc,
      type,
      subscriptionDurationUnit,
      subscriptionDurationMultiplier,
      tieredSubscriptionYN,
      tieredPrice,
      tieredPriceString,
      tieredSubscriptionDurationUnit,
      tieredSubscriptionDurationMultiplier,
      tieredSubscriptionCount,
      showStartDate,
      showEndDate,
      itemImageUrl,
      itemDownloadUrl,
      freeTrialPeriod,
      json,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformProduct decode(Object result) {
    result as List<Object?>;
    return PlatformProduct(
      itemId: result[0]! as String,
      itemName: result[1]! as String,
      itemPrice: result[2] as double?,
      itemPriceString: result[3]! as String,
      currencyUnit: result[4]! as String,
      currencyCode: result[5]! as String,
      itemDesc: result[6]! as String,
      type: result[7]! as String,
      subscriptionDurationUnit: result[8]! as String,
      subscriptionDurationMultiplier: result[9]! as String,
      tieredSubscriptionYN: result[10]! as String,
      tieredPrice: result[11]! as String,
      tieredPriceString: result[12]! as String,
      tieredSubscriptionDurationUnit: result[13]! as String,
      tieredSubscriptionDurationMultiplier: result[14]! as String,
      tieredSubscriptionCount: result[15]! as String,
      showStartDate: result[16]! as String,
      showEndDate: result[17]! as String,
      itemImageUrl: result[18]! as String,
      itemDownloadUrl: result[19]! as String,
      freeTrialPeriod: result[20]! as String,
      json: result[21]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformProduct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(itemId, other.itemId) &&
        _deepEquals(itemName, other.itemName) &&
        _deepEquals(itemPrice, other.itemPrice) &&
        _deepEquals(itemPriceString, other.itemPriceString) &&
        _deepEquals(currencyUnit, other.currencyUnit) &&
        _deepEquals(currencyCode, other.currencyCode) &&
        _deepEquals(itemDesc, other.itemDesc) &&
        _deepEquals(type, other.type) &&
        _deepEquals(subscriptionDurationUnit, other.subscriptionDurationUnit) &&
        _deepEquals(
          subscriptionDurationMultiplier,
          other.subscriptionDurationMultiplier,
        ) &&
        _deepEquals(tieredSubscriptionYN, other.tieredSubscriptionYN) &&
        _deepEquals(tieredPrice, other.tieredPrice) &&
        _deepEquals(tieredPriceString, other.tieredPriceString) &&
        _deepEquals(
          tieredSubscriptionDurationUnit,
          other.tieredSubscriptionDurationUnit,
        ) &&
        _deepEquals(
          tieredSubscriptionDurationMultiplier,
          other.tieredSubscriptionDurationMultiplier,
        ) &&
        _deepEquals(tieredSubscriptionCount, other.tieredSubscriptionCount) &&
        _deepEquals(showStartDate, other.showStartDate) &&
        _deepEquals(showEndDate, other.showEndDate) &&
        _deepEquals(itemImageUrl, other.itemImageUrl) &&
        _deepEquals(itemDownloadUrl, other.itemDownloadUrl) &&
        _deepEquals(freeTrialPeriod, other.freeTrialPeriod) &&
        _deepEquals(json, other.json);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformProduct(itemId: $itemId, itemName: $itemName, itemPrice: $itemPrice, itemPriceString: $itemPriceString, currencyUnit: $currencyUnit, currencyCode: $currencyCode, itemDesc: $itemDesc, type: $type, subscriptionDurationUnit: $subscriptionDurationUnit, subscriptionDurationMultiplier: $subscriptionDurationMultiplier, tieredSubscriptionYN: $tieredSubscriptionYN, tieredPrice: $tieredPrice, tieredPriceString: $tieredPriceString, tieredSubscriptionDurationUnit: $tieredSubscriptionDurationUnit, tieredSubscriptionDurationMultiplier: $tieredSubscriptionDurationMultiplier, tieredSubscriptionCount: $tieredSubscriptionCount, showStartDate: $showStartDate, showEndDate: $showEndDate, itemImageUrl: $itemImageUrl, itemDownloadUrl: $itemDownloadUrl, freeTrialPeriod: $freeTrialPeriod, json: $json)';
  }
}

/// The `SubscriptionPriceChangeVo` fields the public model uses. The prices
/// are NaN when Samsung sends none.
class PlatformSubscriptionPriceChange {
  PlatformSubscriptionPriceChange({
    required this.subscriptionDurationUnit,
    required this.subscriptionDurationMultiplier,
    required this.startDate,
    required this.originalLocalPrice,
    required this.originalLocalPriceString,
    required this.newLocalPrice,
    required this.newLocalPriceString,
    this.isConsented,
    required this.priceChangeMode,
  });

  String subscriptionDurationUnit;

  String subscriptionDurationMultiplier;

  String startDate;

  double originalLocalPrice;

  String originalLocalPriceString;

  double newLocalPrice;

  String newLocalPriceString;

  bool? isConsented;

  /// The SDK enum constant's name, or `""`.
  String priceChangeMode;

  List<Object?> _toList() {
    return <Object?>[
      subscriptionDurationUnit,
      subscriptionDurationMultiplier,
      startDate,
      originalLocalPrice,
      originalLocalPriceString,
      newLocalPrice,
      newLocalPriceString,
      isConsented,
      priceChangeMode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformSubscriptionPriceChange decode(Object result) {
    result as List<Object?>;
    return PlatformSubscriptionPriceChange(
      subscriptionDurationUnit: result[0]! as String,
      subscriptionDurationMultiplier: result[1]! as String,
      startDate: result[2]! as String,
      originalLocalPrice: result[3]! as double,
      originalLocalPriceString: result[4]! as String,
      newLocalPrice: result[5]! as double,
      newLocalPriceString: result[6]! as String,
      isConsented: result[7] as bool?,
      priceChangeMode: result[8]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSubscriptionPriceChange ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(
          subscriptionDurationUnit,
          other.subscriptionDurationUnit,
        ) &&
        _deepEquals(
          subscriptionDurationMultiplier,
          other.subscriptionDurationMultiplier,
        ) &&
        _deepEquals(startDate, other.startDate) &&
        _deepEquals(originalLocalPrice, other.originalLocalPrice) &&
        _deepEquals(originalLocalPriceString, other.originalLocalPriceString) &&
        _deepEquals(newLocalPrice, other.newLocalPrice) &&
        _deepEquals(newLocalPriceString, other.newLocalPriceString) &&
        _deepEquals(isConsented, other.isConsented) &&
        _deepEquals(priceChangeMode, other.priceChangeMode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformSubscriptionPriceChange(subscriptionDurationUnit: $subscriptionDurationUnit, subscriptionDurationMultiplier: $subscriptionDurationMultiplier, startDate: $startDate, originalLocalPrice: $originalLocalPrice, originalLocalPriceString: $originalLocalPriceString, newLocalPrice: $newLocalPrice, newLocalPriceString: $newLocalPriceString, isConsented: $isConsented, priceChangeMode: $priceChangeMode)';
  }
}

/// The `OwnedProductVo` fields the public model uses, with the same rules as
/// [PlatformProduct].
class PlatformOwnedProduct {
  PlatformOwnedProduct({
    required this.itemId,
    required this.itemName,
    this.itemPrice,
    required this.itemPriceString,
    required this.currencyCode,
    required this.type,
    required this.paymentId,
    required this.purchaseId,
    required this.purchaseDate,
    required this.subscriptionEndDate,
    this.subscriptionPriceChange,
    required this.acknowledgedStatus,
    required this.obfuscatedAccountId,
    required this.obfuscatedProfileId,
    required this.json,
  });

  String itemId;

  String itemName;

  double? itemPrice;

  String itemPriceString;

  String currencyCode;

  String type;

  String paymentId;

  String purchaseId;

  String purchaseDate;

  String subscriptionEndDate;

  PlatformSubscriptionPriceChange? subscriptionPriceChange;

  /// The SDK enum constant's name, or `""`.
  String acknowledgedStatus;

  String obfuscatedAccountId;

  String obfuscatedProfileId;

  String json;

  List<Object?> _toList() {
    return <Object?>[
      itemId,
      itemName,
      itemPrice,
      itemPriceString,
      currencyCode,
      type,
      paymentId,
      purchaseId,
      purchaseDate,
      subscriptionEndDate,
      subscriptionPriceChange,
      acknowledgedStatus,
      obfuscatedAccountId,
      obfuscatedProfileId,
      json,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformOwnedProduct decode(Object result) {
    result as List<Object?>;
    return PlatformOwnedProduct(
      itemId: result[0]! as String,
      itemName: result[1]! as String,
      itemPrice: result[2] as double?,
      itemPriceString: result[3]! as String,
      currencyCode: result[4]! as String,
      type: result[5]! as String,
      paymentId: result[6]! as String,
      purchaseId: result[7]! as String,
      purchaseDate: result[8]! as String,
      subscriptionEndDate: result[9]! as String,
      subscriptionPriceChange: result[10] as PlatformSubscriptionPriceChange?,
      acknowledgedStatus: result[11]! as String,
      obfuscatedAccountId: result[12]! as String,
      obfuscatedProfileId: result[13]! as String,
      json: result[14]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformOwnedProduct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(itemId, other.itemId) &&
        _deepEquals(itemName, other.itemName) &&
        _deepEquals(itemPrice, other.itemPrice) &&
        _deepEquals(itemPriceString, other.itemPriceString) &&
        _deepEquals(currencyCode, other.currencyCode) &&
        _deepEquals(type, other.type) &&
        _deepEquals(paymentId, other.paymentId) &&
        _deepEquals(purchaseId, other.purchaseId) &&
        _deepEquals(purchaseDate, other.purchaseDate) &&
        _deepEquals(subscriptionEndDate, other.subscriptionEndDate) &&
        _deepEquals(subscriptionPriceChange, other.subscriptionPriceChange) &&
        _deepEquals(acknowledgedStatus, other.acknowledgedStatus) &&
        _deepEquals(obfuscatedAccountId, other.obfuscatedAccountId) &&
        _deepEquals(obfuscatedProfileId, other.obfuscatedProfileId) &&
        _deepEquals(json, other.json);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformOwnedProduct(itemId: $itemId, itemName: $itemName, itemPrice: $itemPrice, itemPriceString: $itemPriceString, currencyCode: $currencyCode, type: $type, paymentId: $paymentId, purchaseId: $purchaseId, purchaseDate: $purchaseDate, subscriptionEndDate: $subscriptionEndDate, subscriptionPriceChange: $subscriptionPriceChange, acknowledgedStatus: $acknowledgedStatus, obfuscatedAccountId: $obfuscatedAccountId, obfuscatedProfileId: $obfuscatedProfileId, json: $json)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PlatformOperationMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformStoreStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PlatformOwnedProductFilter) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PlatformProduct) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PlatformSubscriptionPriceChange) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PlatformOwnedProduct) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformOperationMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformStoreStatus.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformOwnedProductFilter.values[value];
      case 132:
        return PlatformProduct.decode(readValue(buffer)!);
      case 133:
        return PlatformSubscriptionPriceChange.decode(readValue(buffer)!);
      case 134:
        return PlatformOwnedProduct.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SamsungIapHostApi {
  /// Constructor for [SamsungIapHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SamsungIapHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(
    PlatformOperationMode mode,
    bool showErrorDialog,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.samsung_iap_flutter_android.SamsungIapHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[mode, showErrorDialog],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<PlatformStoreStatus> getStoreStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.samsung_iap_flutter_android.SamsungIapHostApi.getStoreStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlatformStoreStatus;
  }

  /// [productIds] is comma-separated; empty means every product.
  Future<List<PlatformProduct>> getProductsDetails(String productIds) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.samsung_iap_flutter_android.SamsungIapHostApi.getProductsDetails$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[productIds],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<PlatformProduct>();
  }

  Future<List<PlatformOwnedProduct>> getOwnedList(
    PlatformOwnedProductFilter filter,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.samsung_iap_flutter_android.SamsungIapHostApi.getOwnedList$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[filter],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<PlatformOwnedProduct>();
  }
}
