// Copyright (c) 2026 Studio Pyro
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.studiopyro.samsung_iap_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class PlatformOperationMode(val raw: Int) {
  PRODUCTION(0),
  TEST(1),
  TEST_FAILURE(2);

  companion object {
    fun ofRaw(raw: Int): PlatformOperationMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformStoreStatus(val raw: Int) {
  AVAILABLE(0),
  NOT_INSTALLED(1),
  DISABLED(2),
  INVALID(3);

  companion object {
    fun ofRaw(raw: Int): PlatformStoreStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * `ProductVo` field for field. Kotlin sends a missing string as `""` and
 * Dart does all interpretation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformProduct (
  val itemId: String,
  val itemName: String,
  val itemPrice: Double? = null,
  val itemPriceString: String,
  val currencyUnit: String,
  val currencyCode: String,
  val itemDesc: String,
  val type: String,
  val subscriptionDurationUnit: String,
  val subscriptionDurationMultiplier: String,
  val tieredSubscriptionYN: String,
  val tieredPrice: String,
  val tieredPriceString: String,
  val tieredSubscriptionDurationUnit: String,
  val tieredSubscriptionDurationMultiplier: String,
  val tieredSubscriptionCount: String,
  val showStartDate: String,
  val showEndDate: String,
  val itemImageUrl: String,
  val itemDownloadUrl: String,
  val freeTrialPeriod: String,
  val json: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformProduct {
      val itemId = pigeonVar_list[0] as String
      val itemName = pigeonVar_list[1] as String
      val itemPrice = pigeonVar_list[2] as Double?
      val itemPriceString = pigeonVar_list[3] as String
      val currencyUnit = pigeonVar_list[4] as String
      val currencyCode = pigeonVar_list[5] as String
      val itemDesc = pigeonVar_list[6] as String
      val type = pigeonVar_list[7] as String
      val subscriptionDurationUnit = pigeonVar_list[8] as String
      val subscriptionDurationMultiplier = pigeonVar_list[9] as String
      val tieredSubscriptionYN = pigeonVar_list[10] as String
      val tieredPrice = pigeonVar_list[11] as String
      val tieredPriceString = pigeonVar_list[12] as String
      val tieredSubscriptionDurationUnit = pigeonVar_list[13] as String
      val tieredSubscriptionDurationMultiplier = pigeonVar_list[14] as String
      val tieredSubscriptionCount = pigeonVar_list[15] as String
      val showStartDate = pigeonVar_list[16] as String
      val showEndDate = pigeonVar_list[17] as String
      val itemImageUrl = pigeonVar_list[18] as String
      val itemDownloadUrl = pigeonVar_list[19] as String
      val freeTrialPeriod = pigeonVar_list[20] as String
      val json = pigeonVar_list[21] as String
      return PlatformProduct(itemId, itemName, itemPrice, itemPriceString, currencyUnit, currencyCode, itemDesc, type, subscriptionDurationUnit, subscriptionDurationMultiplier, tieredSubscriptionYN, tieredPrice, tieredPriceString, tieredSubscriptionDurationUnit, tieredSubscriptionDurationMultiplier, tieredSubscriptionCount, showStartDate, showEndDate, itemImageUrl, itemDownloadUrl, freeTrialPeriod, json)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      itemId,
      itemName,
      itemPrice,
      itemPriceString,
      currencyUnit,
      currencyCode,
      itemDesc,
      type,
      subscriptionDurationUnit,
      subscriptionDurationMultiplier,
      tieredSubscriptionYN,
      tieredPrice,
      tieredPriceString,
      tieredSubscriptionDurationUnit,
      tieredSubscriptionDurationMultiplier,
      tieredSubscriptionCount,
      showStartDate,
      showEndDate,
      itemImageUrl,
      itemDownloadUrl,
      freeTrialPeriod,
      json,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformProduct
    return MessagesPigeonUtils.deepEquals(this.itemId, other.itemId) && MessagesPigeonUtils.deepEquals(this.itemName, other.itemName) && MessagesPigeonUtils.deepEquals(this.itemPrice, other.itemPrice) && MessagesPigeonUtils.deepEquals(this.itemPriceString, other.itemPriceString) && MessagesPigeonUtils.deepEquals(this.currencyUnit, other.currencyUnit) && MessagesPigeonUtils.deepEquals(this.currencyCode, other.currencyCode) && MessagesPigeonUtils.deepEquals(this.itemDesc, other.itemDesc) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.subscriptionDurationUnit, other.subscriptionDurationUnit) && MessagesPigeonUtils.deepEquals(this.subscriptionDurationMultiplier, other.subscriptionDurationMultiplier) && MessagesPigeonUtils.deepEquals(this.tieredSubscriptionYN, other.tieredSubscriptionYN) && MessagesPigeonUtils.deepEquals(this.tieredPrice, other.tieredPrice) && MessagesPigeonUtils.deepEquals(this.tieredPriceString, other.tieredPriceString) && MessagesPigeonUtils.deepEquals(this.tieredSubscriptionDurationUnit, other.tieredSubscriptionDurationUnit) && MessagesPigeonUtils.deepEquals(this.tieredSubscriptionDurationMultiplier, other.tieredSubscriptionDurationMultiplier) && MessagesPigeonUtils.deepEquals(this.tieredSubscriptionCount, other.tieredSubscriptionCount) && MessagesPigeonUtils.deepEquals(this.showStartDate, other.showStartDate) && MessagesPigeonUtils.deepEquals(this.showEndDate, other.showEndDate) && MessagesPigeonUtils.deepEquals(this.itemImageUrl, other.itemImageUrl) && MessagesPigeonUtils.deepEquals(this.itemDownloadUrl, other.itemDownloadUrl) && MessagesPigeonUtils.deepEquals(this.freeTrialPeriod, other.freeTrialPeriod) && MessagesPigeonUtils.deepEquals(this.json, other.json)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.itemId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.itemName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.itemPrice)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.itemPriceString)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.currencyUnit)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.currencyCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.itemDesc)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subscriptionDurationUnit)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subscriptionDurationMultiplier)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tieredSubscriptionYN)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tieredPrice)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tieredPriceString)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tieredSubscriptionDurationUnit)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tieredSubscriptionDurationMultiplier)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tieredSubscriptionCount)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showStartDate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showEndDate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.itemImageUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.itemDownloadUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.freeTrialPeriod)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.json)
    return result
  }
  override fun toString(): String {
    return "PlatformProduct(itemId=$itemId, itemName=$itemName, itemPrice=$itemPrice, itemPriceString=$itemPriceString, currencyUnit=$currencyUnit, currencyCode=$currencyCode, itemDesc=$itemDesc, type=$type, subscriptionDurationUnit=$subscriptionDurationUnit, subscriptionDurationMultiplier=$subscriptionDurationMultiplier, tieredSubscriptionYN=$tieredSubscriptionYN, tieredPrice=$tieredPrice, tieredPriceString=$tieredPriceString, tieredSubscriptionDurationUnit=$tieredSubscriptionDurationUnit, tieredSubscriptionDurationMultiplier=$tieredSubscriptionDurationMultiplier, tieredSubscriptionCount=$tieredSubscriptionCount, showStartDate=$showStartDate, showEndDate=$showEndDate, itemImageUrl=$itemImageUrl, itemDownloadUrl=$itemDownloadUrl, freeTrialPeriod=$freeTrialPeriod, json=$json)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformOperationMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformStoreStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformProduct.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformOperationMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformStoreStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformProduct -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SamsungIapHostApi {
  fun initialize(mode: PlatformOperationMode, showErrorDialog: Boolean)
  fun getStoreStatus(): PlatformStoreStatus
  /** [productIds] is comma-separated; empty means every product. */
  suspend fun getProductsDetails(productIds: String): List<PlatformProduct>

  companion object {
    /** The codec used by SamsungIapHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `SamsungIapHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SamsungIapHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.samsung_iap_flutter_android.SamsungIapHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as PlatformOperationMode
            val showErrorDialogArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.initialize(modeArg, showErrorDialogArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.samsung_iap_flutter_android.SamsungIapHostApi.getStoreStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStoreStatus())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.samsung_iap_flutter_android.SamsungIapHostApi.getProductsDetails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val productIdsArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getProductsDetails(productIdsArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
