name: samsung_iap_flutter
description: Flutter plugin for Samsung In-App Purchase (IAP)
version: 0.1.0+1


environment:
  sdk: ^3.13.0

flutter:
  plugin:
    platforms:
      android:
        default_package: samsung_iap_flutter_android

dependencies:
  flutter:
    sdk: flutter
  samsung_iap_flutter_android:
    path: ../samsung_iap_flutter_android
  samsung_iap_flutter_platform_interface:
    path: ../samsung_iap_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^11.0.0
